### PR TITLE
Update 1.1 to 1.2

### LINKED ISSUE #64: Update stable devtools protocol to v1.2
Talked this over with dgozman and we agree on this basic approach:

* use current day copy of the protocol
* filter out everything that's experimental or deprecated (incl domains)
* ship as 1.2 (stable)
* remove 1.1

### PR DESCRIPTION
**Pull request by paulirish**
Previewable here: https://paulirish.github.io/debugger-protocol-viewer/

To generate the protocol file I..

1. Took the tot protocol. 
1. Filtered out all experimental domains
1. within remaining domains, i filtered out experimental types, commands, and events.
1. removed the Console domain as its deprecated

I left experimental parameters on methods as it seems fairly odd to exclude those. They also appear in the return value (for `Page.navigate`).

it's viewable here: https://github.com/paulirish/debugger-protocol-viewer/blob/gh-pages/_data/1-2/protocol.json

WDYT?

R=@dgozman, @kdzwinel 

fixes #64

### CODE REVIEW

**Comment by dgozman** [comment]
Looks good! Cross-domain links to types do not work though :-)

- Dmitry

**Comment by paulirish** [comment]
good catch. looks like we've had that bug for a while. :)  konrad just filed as #66

**Comment by linclark** [comment]
It looks like Console was removed because it is deprecated, but the Log entry (which replaces some of the functionality) is still experimental, so that's not included either.

**Comment by kdzwinel** [comment]
Not sure how I feel about 'experimental' flags on something that we call stable, but besides that, LGTM. 👏

The bug that Dmitry mentioned is unrelated. I've created an issue for it #66 .

**Comment by paulirish** [comment]
@linclark good question. filed as #69 so we can followup there.

**Pull request merged**
